let temperatur = ""
serial.redirectToUSB()
basic.forever(function () {
    serial.writeLine("")
    serial.writeLine("         {")
    serial.writeLine("      {   }")
    serial.writeLine("       }_{ __{")
    serial.writeLine("    .-{   }   }-.")
    serial.writeLine("   (   }     {   )")
    serial.writeLine("   |`-.._____..-'|")
    serial.writeLine("   |             ;--.")
    serial.writeLine("   |            (__  \\")
    serial.writeLine("   |             | )  )")
    serial.writeLine("   |             |/  /")
    temperatur = "   |   " + ("" + convertToText(input.temperature()) + " Grad   /  / ")
    serial.writeLine(temperatur)
    serial.writeLine("   |             /  /")
    serial.writeLine("   \\             y'")
    serial.writeLine("    `-.._____..-'")
    serial.writeLine("")
    basic.pause(2000)
})
